version: 1.0
name: Traceable Test-Oriented Multi-Agent Workflow

principles:
  - Architecture precedes tests
  - Tests precede implementation
  - Tests must fail before implementation
  - Traceability is mandatory
  - No silent requirement changes

artifacts:
  architecture: ARCH-XXX
  tests: TEST-XXX
  implementation: CODE
  documentation: DOC

phases:

  - phase: 0
    name: Problem Framing
    owner: human
    description: >
      Human defines the problem, scope, constraints, and success criteria.
    inputs:
      - problem_statement
      - constraints
      - target_language
      - repository_context
    outputs:
      - approved_task_context
    gate:
      rule: human_approval_required

  - phase: 1
    name: Architecture Design
    owner: architect
    description: >
      Produce traceable architectural requirements and interfaces.
    inputs:
      - approved_task_context
    outputs:
      - architecture_spec
    requirements:
      - each_requirement_has_traceability_id: ARCH-XXX
    gate:
      rule: human_approval_required

  - phase: 2
    name: Test Definition (Failing First)
    owner: test_engineer
    description: >
      Define automated tests mapped to architecture.
      Tests must be expected to fail before implementation.
    inputs:
      - architecture_spec
    outputs:
      - test_cases
      - traceability_matrix
    requirements:
      - each_test_references: ARCH-XXX
      - failing_first_statement_required: true
    gate:
      rule: no_implementation_allowed

  - phase: 3
    name: Implementation
    owner: implementor
    description: >
      Implement only what is required to satisfy tests.
    inputs:
      - architecture_spec
      - test_cases
    outputs:
      - implementation_code
      - test_to_code_mapping
    constraints:
      - architecture_immutable: true
      - tests_immutable: true
    gate:
      rule: tests_must_pass

  - phase: 4
    name: Test Validation
    owner: test_engineer
    description: >
      Validate that implementation satisfies all test cases.
    inputs:
      - implementation_code
      - test_cases
    outputs:
      - validation_report
    gate:
      rule: all_tests_pass

  - phase: 5
    name: Documentation & Delivery
    owner: documentor
    description: >
      Summarize completed work and prepare repository updates.
    inputs:
      - validation_report
      - implementation_code
    outputs:
      - delivery_summary
      - git_commit_messages
    gate:
      rule: completion_confirmed

restart_rules:
  - if_tests_change:
      restart_from_phase: 2
  - if_architecture_changes:
      restart_from_phase: 1
  - if_tests_fail_post_implementation:
      restart_from_phase: 3
